### ISSUE TITLE
is it fully port of prerender? but for headless chrome 

### ISSUE THREAD

**Issue by hbakhtiyor** [gwuhaolin/chrome-render#1]

**Comment by gwuhaolin** [comment]
chrome-render can do what pretender do，but base on headless chrome and not compatible with pretender。

**Comment by hbakhtiyor** [comment]
it was clear that base on headless chrome, i meant can prerender's middlewares work with it?

**Comment by gwuhaolin** [comment]
@hbakhtiyor 
I write a koa middleware [koa-seo](https://github.com/gwuhaolin/koa-seo) can replace prerender

**Comment by hbakhtiyor** [comment]
nice
