### ISSUE TITLE
How to setup a Docker container to make it work with this?

### ISSUE THREAD

**Issue by gajus** [gwuhaolin/chrome-render#3]
What would a Docker setup look to make `chrome-render` work in a container?

**Comment by gajus** [comment]
I have tried:

```bash
FROM node:8

# https://askubuntu.com/a/196100/636139
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&\
  sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' &&\
  apt-get update &&\
  apt-get install -y google-chrome-unstable

WORKDIR /srv

COPY package.json .

RUN npm install

COPY . /srv

RUN npm run build

CMD npm run start

EXPOSE 8000

```

But that did not work – I did not get to the bottom of why, but I suspect because of the way I am installing Chrome.

**Comment by gwuhaolin** [comment]
chrome-render is just a lib to be used in other service or lib. When people use docker  most is use to run a service like Database or http-server.
Why you want run chrome-render in docker? What are you doing with it ?
If you want to use it to do SEO, you can see [koa-seo](https://github.com/gwuhaolin/koa-seo).
Maybe We should build a service(and a docker image) like prerender's backend.

**Comment by gajus** [comment]
For the record,

```bash
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
  && apt-get update -y \
  && apt-get install google-chrome-stable -y

```

Works. Note sure what I messed up the first time I tried it.

Why is not important.
