### ISSUE TITLE
Destroy Chrome instance upon SIGINT

### ISSUE THREAD

**Issue by gajus** [gwuhaolin/chrome-render#6]
`chrome-render` should have an option for automatically destroying the allocated Chrome instances upon receiving SIGINT.

```js
const chromeRenderer = await ChromeRender.new({
  maxTab: 1
});

process.on('SIGINT', async () => {
  debug('terminating the associated Chrome instance');

  await chromeRenderer.destroyRender();

  // eslint-disable-next-line no-process-exit
  process.exit();
});

```

I don't think this should be enabled by default, as there could valid use cases for wanting to keep Chrome running after Node.js process terminates. However, a built-in option that enables this behaviour would be nice.

**Comment by gwuhaolin** [comment]
This should be a [chrome-runner](https://github.com/gwuhaolin/chrome-runner) feature, chrome-render depend on chrome-runner.

I will add this feature to chrome-runner later. BTW Would you like help me add it to chrome-runner?

chrome-runner should handle process on exit event( not only SIGINT event), before process exit kill chrome child process.

**Comment by gajus** [comment]
> I will add this feature to chrome-runner if I has free time, chrome-runner also dev by me. BTW Would you like help me add it to chrome-runner?

Sorry, I have my hands full in open-source.

I suggest taking a look at https://www.npmjs.com/package/death for a simple abstraction that will handle all exit scenarios.

**Comment by gwuhaolin** [comment]
fixed in https://github.com/gwuhaolin/chrome-runner/commit/2bcda5616b970da38fdb26dfc41ee39a2f3355cd

just reinstall your chrome-render to fix this issue.

**Comment by gajus** [comment]
Awesome. Thank you.
